---
title: "p8105_hw6_st3117"
author: "Sha Tao"
date: "November 15, 2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)
library(httr)

theme_set(theme_bw())

```

## Problem 2_1

```{r p2_1}

p2_dataset = 
  RCurl::getURL("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv") %>%
    read_csv()

```

## Problem 2_2

```{r p2_2}

homicides =
  p2_dataset %>% 
  mutate(victim_race = fct_relevel(ifelse(victim_race == "White", "white", "non-white"), "white"),
         victim_age = ifelse(victim_age == "Unknown", NA, as.integer(victim_age)),
         victim_sex = as.factor(victim_sex),
         city_state = paste(paste0(city, ","), state),
         resolved = as.numeric(disposition == "Closed by arrest")) %>% 
  filter(!city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL")) %>% 
  select(uid, victim_race, victim_age, victim_sex, city_state, resolved)


```

## Problem 2_3
```{r p2_3}

baltimore_logistic = 
  homicides %>%
  filter(city_state == "Baltimore, MD") %>% 
  glm(resolved ~ victim_age + victim_sex + victim_race, data = ., family = binomial()) 

# save baltimore_logistic as an object
save(baltimore_logistic, file = "Baltimore_logistic.RData")

baltimore_logistic %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate),
         conf.low = exp(estimate - 1.96 * std.error),
         conf.high = exp(estimate + 1.96 * std.error)) %>% 
  filter(term == "victim_racenon-white") %>% 
  select(beta = estimate, p.value, OR, conf.low, conf.high) %>% 
  knitr::kable(digit = 3)

```

## Problem 2_4

```{r}

# create function for all city glm
city_logistic = function(x){
  
    homicides %>% 
    filter(city_state == x) %>% 
    glm(resolved ~ victim_age + victim_sex + victim_race, data = ., family = binomial())  %>% 
    broom::tidy() %>% 
    mutate(OR = exp(estimate),
           conf.low = exp(estimate - 1.96 * std.error),
           conf.high = exp(estimate + 1.96 * std.error)) %>% 
    filter(term == "victim_racenon-white") %>% 
    select(beta = estimate, p.value, OR, conf.low, conf.high)

}

# compute city proportion test
city_result = 
  tibble(city_state = unique(homicides$city_state)) %>% 
  mutate(map(.x = unique(homicides$city_state), ~city_logistic(.x))) %>% 
  unnest


```

## Problem 2_5
```{r}

city_result %>% 
  ggplot(aes(x = reorder(city_state, OR), y = OR)) +
    geom_point() +
    geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.3, size = 7)) +
    labs(
      x = "City",
      y = "Odds Ratio",
      title = "Estimated Odds Ratio for Solving Homicides Comparing Non-white Victims to White Victims"
    )

```





